[alembic]
script_location = alembic
prepend_sys_path = .
path_separator = os
file_template = %%(rev)s_%%(slug)s

[loggers]
keys = root,alembic
[handlers]
keys = console
[formatters]
keys = generic
[logger_root]
level = WARN
handlers = console
[logger_alembic]
level = INFO
handlers =
qualname = alembic
[handler_console]
class = StreamHandler
args = (sys.stderr,)
formatter = generic
[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
